### ISSUE TITLE
Impact metrics

### ISSUE THREAD

**Issue by guivivi** [paytonjjones/networktools#2]
Dear Payton,

Thank you for your very nice package. My question is about the impact() function. As the reference manual says, it is not possible to use it with a network object, such as one of igraph class. Do you know if this function can be tweaked to be used with networks? My data is a collection of source and target nodes, so it would be interesting if I could compute somehow these impact values.

Guillermo

**Comment by paytonjjones** [comment]
Guillermo,

I apologize for not responding earlier, somehow I missed this. You can transform an igraph class network to an adjacency matrix by using the getWmat() function from qgraph. 

FYI, I will be deprecating and removing the impact() function in an upcoming release due to limited usage and a related dependency issue.
